// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0m0PdYbdtj_XJ-9x5sMM8MlU0c5nagv8',
    appId: '1:341897187439:web:b00e66b585578a14947d9a',
    messagingSenderId: '341897187439',
    projectId: 'fluttertrip-c3ddb',
    authDomain: 'fluttertrip-c3ddb.firebaseapp.com',
    storageBucket: 'fluttertrip-c3ddb.appspot.com',
    measurementId: 'G-BL0FSG9DTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB4kQ6LiRLNdBIlnWTMVAXqh8m4KHXo4k',
    appId: '1:341897187439:android:e2657bd5f2855c89947d9a',
    messagingSenderId: '341897187439',
    projectId: 'fluttertrip-c3ddb',
    storageBucket: 'fluttertrip-c3ddb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlM2Cd2hIqtyQ5PXSf3Y6Klkc3PEyeuAA',
    appId: '1:341897187439:ios:6795cb993d51e0ed947d9a',
    messagingSenderId: '341897187439',
    projectId: 'fluttertrip-c3ddb',
    storageBucket: 'fluttertrip-c3ddb.appspot.com',
    iosBundleId: 'com.example.ios.fluttertrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlM2Cd2hIqtyQ5PXSf3Y6Klkc3PEyeuAA',
    appId: '1:341897187439:ios:6795cb993d51e0ed947d9a',
    messagingSenderId: '341897187439',
    projectId: 'fluttertrip-c3ddb',
    storageBucket: 'fluttertrip-c3ddb.appspot.com',
    iosBundleId: 'com.example.ios.fluttertrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0m0PdYbdtj_XJ-9x5sMM8MlU0c5nagv8',
    appId: '1:341897187439:web:a463044760b93e20947d9a',
    messagingSenderId: '341897187439',
    projectId: 'fluttertrip-c3ddb',
    authDomain: 'fluttertrip-c3ddb.firebaseapp.com',
    storageBucket: 'fluttertrip-c3ddb.appspot.com',
    measurementId: 'G-6NRQTZS0ZB',
  );
}
